exhibit_titles: ['Πάπυρος του Δερβενίου', 'Χρυσό στεφάνι μυρτιάς', 'Κρατήρας του Δερβενίου']
exhibit_codes: ['a', 'b', 'c']
exhibit_rasa_upfile: ['rasa_papyrus_up.sh', 'rasa_wreath_up.sh', 'rasa_crater_up.sh']
exhibit_rasa_downfile: ['rasa_papyrus_down.sh', 'rasa_wreath_down.sh', 'rasa_crater_down.sh']
exhibit_rasa_restartfile: 'rasa_restart.sh'
